### ISSUE TITLE
Adopt doc8 style checker

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1000]
We have to integrate this into our CI:
https://github.com/openstack/doc8

We have a Travis job to check for missing docs files so another job in the same section is probably where this needs to go.

**Comment by atodorov** [comment]
cc @Prome88 - I know you will like doc8

**Comment by Prome88** [comment]
Ran it with default settings in Kiwi/docs/source directory.
========
Total files scanned = 127
Total files ignored = 0
Total accumulated errors = 7039
Detailed error counts:
    - CheckCarriageReturn = 3482
    - CheckIndentationNoTab = 0
    - CheckMaxLineLength = 74
    - CheckNewlineEndOfFile = 0
    - CheckTrailingWhitespace = 3482
    - CheckValidity = 1

The validity issue is in changelog.rst:2: D000 Duplicate explicit target name: "issue #889". I'll check the file and fix the issue.

As for other issues I need to check on one Linux VM if the file format issues are due to my Windows GIT settings and also dabble into documentation of  doc8 to see which errors are really relevant.

**Comment by Prome88** [comment]
@atodorov is the Travis part acceptable or it should invoke CMD and the doc8 install / script should be placed in makefile like other tests?

**Comment by atodorov** [comment]
- add doc8 into requirements/devel.txt and it will be installed automatically
- we do need a target in Makefile b/c that will allow to execute doc8 locally as well.
^^^ for now probably a separate target in Makefile and separate stage in Travis (allow failures) b/c there are many things that will need fixing/investigation. Later merge doc8 with either `make docs` or `make check-docs-source-in-git` (and rename to `check-docs`).

**Comment by Prome88** [comment]
_Add new file_ 
doc8.ini
```
[doc8]
path=/docs/source 
```

_Add lines:_
requirements/devel.txt  <--  should this rather go to requirements/readthedocs.txt 
```
doc8
```

makefile
```
.PHONY: doc8
	doc8 --config="doc8.ini"
```


.travis.yml
```
jobs:
  allow_failures:
  - env: CMD=doc8

```
```
    - stage: non_functional_testing
      env:
        - CMD=doc8
```
