### ISSUE TITLE
XMLRPC API issues

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#116]
### Description of problem
So far I've noticed a couple of issues, haven't use the API excessively, just quick look.

1. Errors are not being handled properly - tcms/xmlrpc/dispatcher.py
               ` xmlrpc.client.Fault(1, "%s: %s" % (sys.exc_type.__name__, sys.exc_value)),`
exc_value does not exist in Python 3, so it causes an exception and results in response 500 to the client without any details.
Proposed fix to change last (line 98) "except" clause to:
`        except Exception as e:
            response = xmlrpc.client.dumps(
                xmlrpc.client.Fault(1, "%s" % (e)),
                allow_none=self.allow_none, encoding=self.encoding)`

2. Some objects have "bad" objects. As example, I used TestRun.get method and in response there is "tag" field which is "map object". So it causes "map object cannot be marshalled" exception. As a workaround, I've just removed "tag" from response, but probably it should be "marshallable"?
![image](https://user-images.githubusercontent.com/918446/32601559-5bb34032-c543-11e7-9391-07599b15b99a.png)
Probably it's applicable to some other methods as well...

3. Is there any way to disable\remove HTTPS? Since we want to deploy the tool only internally for small team, we don't care about certificates and all the stuff. But it adds some pain trying to get API working without any secure connections...

### Component (web, API, etc)
API

**Comment by atodorov** [comment]
Thanks for the bug report. I am actually working on bringing the api client up to speed. I've also found a few places on the server side that needed to be fixed. Let's revisit once these are pushed to master.

**Comment by GodfatherThe** [comment]
Other opens about API:
- Field "Product" is required for TestCase.create, but in the same time there is no such a field in TestCase by itself because there is 1:N relationship between Case and Plans. So I would expect to require "plan" when creating TestCase.
- Fields `test_cases.script and notes` are required to be NOT NULL, so method TestCase.create fails when they're not specified

**Comment by atodorov** [comment]
Update: I've made quite a few changes related to the client side API, some more are coming very soon. The gist is that we now have an API client library, which was brought back from the original upstream project. I've decided to keep it under the same source code repo to facilitate testing. 

The client is Python2/3 compatible, however only Python 3 is currently tested. I'm not certain that I will keep Python 2 compatibility much longer so please use Py3 for your testing if possible.

Changes that are on my todo:
- Use a generic class name like TCMS for the API objects to avoid infringing any potential copyright of the upstream copy.
- Drop caching support and force the api client to issue requests to the server every time.
- produce a package for PyPI
- merge the API docs sources into the existing documentation
- merge API README/history and license into the existing files or make it clear which is what. ATM we just have a bunch of files that landed here during the merging of the two code bases.

I believe 1) and 2) above were fixed with the changes from #124.

3) is a feature request so please file it separately.

From your second comment:

I think all of these are valid issues, the tests one being solved already I believe. Can you file them separately so that we can investigate and keep track for each one of them.

**Comment by GodfatherThe** [comment]
Created #126, about HTTPS I spent several days trying to figure out how to start it, but finally I've got my API script working on both local and production, so it's ok.
