### ISSUE TITLE
Use bug tracker integration to show bugs details

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#117]
### Description of problem
There is bug tracker integration, but looks like it's almost not used. At least I would expect to see bugs names in runs or reports, not just ID with link

### Component (web, API, etc)
WEB

**Comment by atodorov** [comment]
This is a reasonable request.

Do you prefer to store the names in the database where they can get out of sync with the bug tracker or to fetch the names when we display the bugs (possibly slowing down b/c we have to talk to an external system)?

**Comment by GodfatherThe** [comment]
As for the moment, any page related to bug trackers is being loaded pretty slow, because JIRA.jira (we use this bug tracker) object is initialized every time from scratch. So it's not very fast anyway =)
A quick but valuable solution is just to call BT every time, and optimization may follow after that, if there is a bottleneck.

**Comment by purush-github** [comment]
Hi i just created a github account and then i used same login credentials for using kiwitcms. I created Test plan,Test cases, Test runs.. But i am not able link JIRA tickets to the test cases. I am able to Add jira ticket by clicking on ADD under Bug, but when i click on the ticket number it is showing you need to  Enable linking test cases by configuring API parameters for this Issue Tracker! 

Please help me out in this issue.

**Comment by atodorov** [comment]
There is baseline implementation for this feature which provides defaults (via OpenGraph) for each issue tracker. Specific overrides for each individual issue tracker type (e.g. Jira, Bugzilla) may be provided (either modifying the app) or as additional features later.

There is both server side cache (can be anything, Django is flexible in this regard; can be used instead of DB from an external script that syncs the information) and browser side cache to try speeding up these operations.

Closing. Anything else is out of scope for this particular issue.
