### ISSUE TITLE
View attachment fail with 500 ISE

### ISSUE THREAD

**Issue by Ariusxiang** [kiwitcms/Kiwi#160]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
https://demo.kiwitcms.org/case/71/#attachment

### Component (web, API, etc)
web

### How often reproducible
100%

### Steps to Reproduce

1. Browse into a test case
2. upload a png file as attachment
3. view the uploaded file on step 2

### Actual results
500 ISE error page

### Expected results
Showing the attachment or download the attachment

**Comment by calvinmqc** [comment]
I noticed another issue with 4.1.0 version:

Browse into a test plan > test case > Attachment
Click the add button besides "Add attachment"
It redirects me to the login page right away (not show the wizard to select attachment)

If I use root account, this issue does not happen. Initially I thought this is related to the user permissions. Therefore I tested it as below:

Login as root, go to Groups, go to Tester
Add all available permissions on the left panel to the right panel
Save
Login again as one user under Tester group, try to add attachment and the issue is still the same

Login as root, go to Users, click the test user
Add all available permissions on the left panel to the right panel
Save
Login again as the test user I just modified, add an attachment but the issue is still the same

However, if I go to Users, click the test user, check the Superuser option, save it. Then the issue does not reoccur. So it looks like only super user (root) can add attachment successfully in this version.

I do plan to upgrade to the latest version. But when I check the release note, it does not mention this issue so I assume it will still be the same even after I upgrade to the latest version.

Any suggestion? Thanks for your time! @atodorov

**Comment by atodorov** [comment]
@calvinmqc please retest with the latest 4.1.4 version and report as a new issue if you still see problems.

**Comment by calvinmqc** [comment]
I upgrade to 4.1.4 version today and test the attachment feature.
There is no change. I can reproduce the issue with the previous steps.
It is exactly the same symptom so I think it is a bug.

**Comment by andyflury** [comment]
The issue still seems to be there with the latest docker image.
I still get a 500 ISE error page when trying to upload files (even with the root account)
Is there maybe an older version of Kiwi that I can use where uploads still worked ?

**Comment by arafuls** [comment]
I am still getting this issue, has it been fixed?

Users with appropriate permission still cannot view or add attachments unless they are promoted to superuser..

**Comment by atodorov** [comment]
@arafuls this is a fairly old issue. Open a new one and provide more information as per the bug template. Also make sure you are using the latest version (which is 8.3 at the moment).
