### ISSUE TITLE
Include support for child Test Plans in Status Matrix

### ISSUE THREAD

**Issue by ronfeldman** [kiwitcms/Kiwi#1683]
**Problem**
When using Child Test Plans, it is difficult to get an overall view of the Parent Test Plan status in the Status Matrix.

**Solution**
When a Parent Test Plan is selected, show the Test Runs and Test Executions for both the Parent TP and its Children TPs.
Also, provide a visual cue that a TC and a TR is from a Child TP.

If the Parent/Child presentation could be collapsible/expandable, that would be nice, but not necessary.

**Comment by atodorov** [comment]
> If the Parent/Child presentation could be collapsible/expandable, that would be nice, but not necessary.

With the existing UI and data organization this is not straight forward. It would require rethinking the entire data structure underneath. However a visual clue should work reasonably fine for now, see the attached screenshots:

Here TE-366 is shown as normal because TR-29 is directly related to the chosen TP:
![not_including_children](https://user-images.githubusercontent.com/1002300/86600210-6e0d5580-bfa8-11ea-8210-0f8dbc352c99.png)

Here the filter opts in showing results from TRs which are related to TPs that are children to the selected one. TE-366 is now shown differently - an icon prefix & background change - to indicate that it is coming from the parent. The rest of the cells are from child TPs/TRs in this example:
![including_children](https://user-images.githubusercontent.com/1002300/86600312-9006d800-bfa8-11ea-9f7b-65290cffd478.png)
