### ISSUE TITLE
User cannot add attachment

### ISSUE THREAD

**Issue by arafuls** [kiwitcms/Kiwi#1706]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
A user with appropriate permissions (or even all permission) cannot add an attachment.

### Version or commit hash (if applicable)
8.3

### Steps to Reproduce
1.  Open test run case
2. Add attachments
![image](https://user-images.githubusercontent.com/33244304/83063677-85af0100-a02e-11ea-86d2-f945059c5be7.png)

### Actual results
Redirected to login dashboard

### Expected results
To be able to upload supporting files for a test case

### Additional info (Python traceback, logs, etc.)
Even with all permissions granted, a user cannot add attachments unless granted superuser privileges.

**Comment by atodorov** [comment]
What you have posted is **NOT** version 8.3 because it doesn't look like that. Here's how it looks:

![tr_tc_attachments](https://user-images.githubusercontent.com/1002300/83117991-708dad00-a0d6-11ea-8756-1dd4d49ee203.png)

See the **Bugs and hyperlinks** section which is above **Attachments**. This is missing in your screenshot so either you are using an older version or you are not showing me the correct screenshot.

Reopen when you can reproduce on public.tenant and post the correct screenshot with the latest version.
