### ISSUE TITLE
Tags are case-sensitive when searching - should allow broader matching

### ISSUE THREAD

**Issue by ronfeldman** [kiwitcms/Kiwi#1851]
### Tag case-sensitivity is inconsistent
Adding a tag with the same string but different case is not permitted
Searching for a tag with matching string but different case fails to find a match

### Version or commit hash (if applicable)
Tested on Live Demo, 8.5-Enterprise

### Steps to Reproduce

1. Add a tag to Test Plan X, "Sample_TAG"
2. Search for Test Plans with tag "Sample_TAG"
3. Search for Test Plans with tag "sample_tag"
4. Add a tag to a Test Plan X, "sample_tag"

### Actual results
Step 1: successfully adds tag
Step 2: finds Test Plan X
Step 3: does not find Test Plan X
Step 4: Does not add tag "sample_tag" to Test Plan X

### Expected results
Step 3 should succeed (preferable)

_or_

Step 4 should succeed

**Comment by atodorov** [comment]
For Steps 1 and 4 above I am able to add both "Sample_TAG" and "sample_tag" strings to a TP:
https://public.tenant.kiwitcms.org/plan/3142/web-app-sanity-checks#tag

Same for a TC which uses a new widget for tags:
https://public.tenant.kiwitcms.org/case/9671/

The two tag objects are 2 different records in the database:
"sample_tag" -> https://public.tenant.kiwitcms.org/admin/management/tag/372/change/
"Sample_TAG" -> https://public.tenant.kiwitcms.org/admin/management/tag/338/change/

So tags **are** case sensitive when adding them as can be seen from the examples above. 


For search pages the query used in `tag__name__in` and compared against a list of the values entered. This indeed requires to type the search values exactly as they are in the database. Will look into it.

**Comment by atodorov** [comment]
Additional information:

- The `tag__name__in` lookup doesn't allow for wildcard matching and is also used internally as a form field name
- `tag__name__icontains` lookup doesn't allow for multiple values
- A possible workaround would be modifying the behavior to use `icontains` when there is only 1 value entered (broader match) but that would result in a different behavior when there are values separated by comma (they will need to match exactly). Confusing IMO and source of more issues down the line.
- All search criteria are AND-ed together. The underlying ORM supports more complex expressions like OR but ATM the API layer doesn't have any syntax to describe these. This is initially described in https://github.com/kiwitcms/Kiwi/issues/465#issuecomment-713552311 and should be explored into more details b/c it is not a trivial change.

@ronfeldman can you explain your original use-case so we can see of there is a quick fix. Otherwise we'll morph this issue into RFE for a more advanced query mechanism via the API.

**Comment by ronfeldman** [comment]
I think I was using it to keep track of the state of test cases as I was creating/updating/finalizing several of them at the same time. I was using tags to remind me where I was at in that process (sort of a finer tuned version of the current Status field, with different states added between Proposed/Need Update/Confirmed).

While it's unexpected behavior (i.e. a defect) I'd say that the impact is very low, so however you want to classify it would be fine with me.

**Comment by atodorov** [comment]
@ronfeldman got it, thanks.

For customizable Test Case statuses follow https://github.com/kiwitcms/Kiwi/issues/1932.

The search case would be converted into a bigger issue requesting support for OR queries via API and search pages.

**Comment by atodorov** [comment]
https://github.com/kiwitcms/Kiwi/issues/2048
