### ISSUE TITLE
404 On users & groups page

### ISSUE THREAD

**Issue by avishnyak** [kiwitcms/Kiwi#1956]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
When I try to edit users on my private tenant, I get a 404 page when clicking "Admin" -> "User and groups"

### Version or commit hash (if applicable)
8.7-Enterprise

### Steps to Reproduce

1. Login to https://atlaslifttech.tenant.kiwitcms.org/admin/auth/
2. Open Admin -> Users and groups

### Actual results
404 Page Not Found

### Expected results
Ability to set up users and groups.

### Additional info (Python traceback, logs, etc.)

Also, under Plugins -> Tenant -> Authorize Users I see a list of what looks like all public instance users.  Not sure if that's intended.
![image](https://user-images.githubusercontent.com/6599079/93812150-11642300-fc06-11ea-96e8-fac7e6e1f7f7.png)

**Comment by atodorov** [comment]
> When I try to edit users on my private tenant, I get a 404 page when clicking "Admin" -> "User and groups"

You can't edit users because all accounts and groups are stored on the public tenant and there are not only emails but also permission assignments so only super-user accounts can access this. 

Per tenant groups and permissions is discussed at https://github.com/kiwitcms/tenants/issues/104 if you want to follow.

> Also, under Plugins -> Tenant -> Authorize Users I see a list of what looks like all public instance users. Not sure if that's intended.

Yes, this is working as designed. You can select other accounts and grant them access to your own tenant.  The interface could be improved though. I've opened https://github.com/kiwitcms/tenants/issues/114 for that.
