### ISSUE TITLE
Bug tracker integration with Azure DevOps

### ISSUE THREAD

**Issue by avishnyak** [kiwitcms/Kiwi#1979]
**Is your feature request related to a problem? Please describe.**
Would like the be able to 1-click file a bug from Kiwi to Azure DevOps.

**Describe the solution you'd like**
A bug tracking system integration with Azure DevOps.  The ability to traverse links back and forth to the two systems.
Nice to have: bug status integration between the two systems
Nice to have: Ability to automatically generate a test run from an Azure Pipeline release "manual step"

**Describe alternatives you've considered**
The only alternative I can come up with is manual double-entry.

**Additional context**
DevOps REST API: https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1
TestRails integration w/DevOps: https://www.gurock.com/testrail/docs/integrate/tools/azure-devops
Jira integration w/DevOps: https://devblogs.microsoft.com/devops/azure-pipelines-integration-with-jira-software/

**Comment by atodorov** [comment]
@avishnyak we aren't very familiar with Azure DevOps services. Can you provide us with links to which particular service you are using ? Do you mean the **Azure Boards** service? e.g. using their kanban cards to represent bugs ?

**Comment by avishnyak** [comment]
Yes, that's there one. They renamed it to DevOps.

**Comment by atodorov** [comment]
Kiwi TCMS needs help with implementing bug tracker integration with Azure Boards service. The way Kiwi TCMS integrates with external bug tracking systems is documented at https://kiwitcms.readthedocs.io/en/latest/modules/tcms.issuetracker.html#module-tcms.issuetracker with the basic methods documented in https://kiwitcms.readthedocs.io/en/latest/modules/tcms.issuetracker.base.html (also see other modules for more examples).

**Definition of Done**:
- The following features must be supported:
  - 1-click bug report
  - automatic bug update with manual fallback
  - show bug info
- Implementation is in `tcms/issuetracker/azure_boards.py`, class `AzureBoards` + add the new dotted path to `EXTERNAL_BUG_TRACKERS` setting.

- It doesn't looks like Microsoft provides an official API client library in Python for the Azure Boards service. Very likely the API calls would need to be handled internally. The starting API documentation is at:

https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/Work%2520Items?view=azure-devops-rest-5.0&viewFallbackFrom=azure-devops

- Automated tests:
  - job definition is in .github/workflows/integration_bugtracker.yml
  - Docker + test data setup is in `tests/<...>` - follow the other examples there
  - Actual test code is in `tcms/issuetracker/tests/` - follow the other examples there
  - Preferably we use a Docker container for the test. If that's not possible then we'll setup an Azure account for testing purposes and the API secret(s) will be provided to the CI job. For development you can use your own instance. **NOTE: there are the Start free/Start free with GitHub buttons** at the top of the Azure Boards service page.
- CI pass
- All code review passed & PR merged

Hints:
- Azure Boards starting page - https://azure.microsoft.com/en-us/services/devops/boards/
- Devel getting started docs: https://kiwitcms.readthedocs.io/en/latest/contribution.html#testing
- Django testing documentation: https://docs.djangoproject.com/en/3.1/topics/testing/

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

**Note:** this is a 200 EUR bounty.

**Comment by atodorov** [comment]
> Yes, that's there one. They renamed it to DevOps.

@avishnyak thanks. I've added our standard opensource bounty text + definition of what needs to be done in case someone wants to tackle this before the core team gets to it.

**Comment by cmbahadir** [comment]
I would like to pull this item if nobody has already started to work on it.

**Comment by atodorov** [comment]
@cmbahadir go ahead. I have assigned this issue to you!
