### ISSUE TITLE
Test Plan - slow(er) loading of test cases on GUI

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#2078]
###Description of problem

New test plan loads all test cases at once instead of loading them by 100's like in previous version.

In case of test plan with 800 test cases (and as many images attached to test plan) this makes a significant difference on initial load.

8.6 - 
![image](https://user-images.githubusercontent.com/25688732/98545943-82cf6200-2296-11eb-851f-08e998c71bb6.png)

8.8 - 
![image](https://user-images.githubusercontent.com/25688732/98545890-71865580-2296-11eb-941a-4071483c25f6.png)

### Version or commit hash (if applicable)
v8.8

### Steps to Reproduce

1. Open Test Plan with larger amount  of(more than 100) test cases

### Actual results
See description.

### Expected results
See description.

**Comment by atodorov** [comment]
The numbers are misleading for several reasons but most importantly you are comparing apples to oranges.

In version 8.6 the test plan page is loading IIRC only 100 rows at a time while in 8.8 it loads 800 rows according to your comment. Thus a 2x slower DOM is actually 4x faster per the same amount of data. 

OTOH a 8x total load time in v8.8 is compared to v8.6 which contains far less asynchronous operations. And it is important to point that out because asynchronous loading will let you see the page faster and probably perform some of the actions before the page is completely loaded (I haven't tried this out). 

In addition v8.8 is loading not only more rows together but also more auxiliary information like tags, components, attachments, etc (if they exist). Some are loaded on demand others are loaded together with the main page.

Simply put when you have more data on the page it will take more time to load. 

The only actionable way forward here is to take samples of the same page using the latest version and compare loading of 100 rows vs. 1000 rows so we can search for places which are sub-optimal (for example search pages load tags in a very non-optimal way causing hundreds of additional transactions instead of loading all of them at once).

The other thing to look for is how much of the time spent loading is actually blocking the browser from displaying the page and allowing the tester to interact with it. Also which exactly interactions if there is a substantial difference. Because if you can interact with the page there's nothing wrong with the browser loading stuff in parallel. 


Without the information requested above there isn't much we can do about this issue.

**Comment by Prome88** [comment]
Unfortunately I don't have the time to go and investigate this into further details and we are satisfied with v8.6 so I'm closing this.

Also some clarifications on the issues you've raised:

- v8.6  Total time before user can interact with all functions on the page (for the first 100 cases) - 4 seconds
- v8.8  Total time before user can interact with all functions on the page (all cases) - 30+ seconds
     - Attachments - 3s
     - Tags - 7s
     - Test cases - 30s+
