### ISSUE TITLE
Internal Error: Field 'id' expected a number but got 'undefined' when remove a component on testcase page

### ISSUE THREAD

**Issue by shiron-truong** [kiwitcms/Kiwi#2145]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
It shows Internal Error: Field 'id' expected a number but got 'undefined' when remove component on testcase page.

### Version or commit hash (if applicable)
https://public.tenant.kiwitcms.org/case/10227/#components

### Steps to Reproduce

1. Open a testcase, e.g: https://public.tenant.kiwitcms.org/case/10227
2. Add a component (which doesn't reload the page)
3. Click remove the recent added component

### Actual results
a error popup will show.

### Expected results
remove the component

### Additional info (Python traceback, logs, etc.)
I can remove the component if reload the page.
![remove_component](https://user-images.githubusercontent.com/50346670/101886881-b3285a00-3bce-11eb-927b-0ad2d72c798d.gif)

**Comment by atodorov** [comment]
> a error popup will show.

The root cause is likely that the component ID isn't added properly when the row is rendered or the JS code doesn't read it properly when immediately trying to remove it.

**Comment by asankov** [comment]
workaround: refresh the page and the deletion succeeds. 

this finding tells me that this is a bug in the JS code that adds the component to the table upon adding in from the UI

**Comment by pandafy** [comment]
Hey! I would like to work on this but I am not able to add a component on https://public.tenant.kiwitcms.org/. Is there a way to create a component?

**Comment by pandafy** [comment]
I believe that this bug developed due to inconsistencies in the signatures of `TestCase.add_component(case_id, component)` and `TestCase.remove_component(case_id, component_id)`. 

IMO, this bug can be solved in two ways: 

1. Alter the modify the return signature of `TestCase.add_component` such that it explicitly return the component which was added instead of returning complete serialised `TestCase` object. Then we can do 
```js
to_table.row.add({name: _name, id: data.component.id}).draw()
```
instead of https://github.com/kiwitcms/Kiwi/blob/aa22c2f1f299d4c16585726d1d5f2208a1a741a4/tcms/testcases/static/testcases/js/get.js#L10

2. Alter the signature of `TestCase.remove_component` and use `case_id` and `component_name` as arguments, similar to `TestCase.add_component`. This will remove our dependency on `component.pk` hence, we will be able to use the name of component which is already available. 

@atodorov @asankov what do you think about above implementations?

**Comment by atodorov** [comment]
> IMO, this bug can be solved in two ways:
> 
>     1. Alter the modify the return signature of `TestCase.add_component` such that it explicitly return the component which was added instead of returning complete serialised `TestCase` object. Then we can do
> 


Yup, this function needs to return a serialized Component instead of a TestCase object. Make the change, it will play nicely with my changes in #2207. Both of which will break API compatibility but the next  Kiwi TCMS version will be a major version anyway.
