### ISSUE TITLE
Don't send notifications for actions performed by myself

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#216]
At the moment all actions are leading to notifications. But it doesn't seem useful when I'm creating\updating my test run by my own. It would be nice to have the same approach as Jira has - notify only if the item assigned to you AND the change was made by any other person except you.

**Comment by atodorov** [comment]
This is a valid use-case, thanks for the suggestion. However it is not currently possible to implement. All email notifications are sent from post_save signals (which are issued internally by Django) and they are missing information about the current user performing the action.

I am looking at django-papertrail to see of it can help resolve this issue. So far it doesn't seem to be technically possible (in an elegant way) to have all the necessary information so that the signal handler sending the emails can perform a test like `if changed_by != myself then send_email`.

I will continue to investigate, there's got to be an easier solution for this. 

FYI https://github.com/FundersClub/django-papertrail/issues/10

**Comment by atodorov** [comment]
Note: with the introduction of model history tracking we now have a pre_save signal handler that adds a reference to the old version of the model (for calculating the changelog automatically). This is true for all models that keep history.

This old instance should be available for post_save handlers that send emails.

**Comment by atodorov** [comment]
For reference HistoryRequestMiddleware sets HistoricalRecords.thread.request
