### ISSUE TITLE
Show error popup when change status in test run page 

### ISSUE THREAD

**Issue by shiron-truong** [kiwitcms/Kiwi#2197]
### Description of problem
Show error popup when change status in test run page 

### Version or commit hash (if applicable)
https://public.tenant.kiwitcms.org/runs/2799/

### Steps to Reproduce

1. access a test run page
2.click to Status button

### Actual results
![image](https://user-images.githubusercontent.com/50346670/104543120-687b8100-5657-11eb-928f-adf3aa56bcdc.png)

### Expected results
Change status without popup error

**Comment by atodorov** [comment]
This is working as designed. The error message happens because the input data can't be validated. 

For TR-2799 Build "unspecified" (id 2941) points to Version unspecified. OTOH the TR has Product ACEFLOW and Version 2.0.0.1 (id 3644).  When you click the status button it sends an API request to the backend which tries to validate if the build field is tied to a Version 2.0.0.1 which it isn't and fails. 

The reason for this is that this TR has been created before the upgrade to Kiwi TCMS v9.0 where we didn't have enough information about Build-Version relationships. The only solution is to manually edit the TR and create an appropriate Build record (indeed when you try to edit the TR it shows no related builds to version 2.0.0.1).
