### ISSUE TITLE
Expose WSGI for better integration with reverse proxy (nginx)

### ISSUE THREAD

**Issue by mrdeveloperdude** [kiwitcms/Kiwi#2494]
When running kiwi behind nginx as a reverse proxy there is an unecessary overhead of running apache. If WSGI was exposed, it could be integrated directly for performance and simplicity benefit.

One way to solve this would be to create a separate "core" dockerfile/image that exposes WSGI and then wrap that in another dockerfile/image that has the apache layer.

**Comment by atodorov** [comment]
> One way to solve this would be to create a separate "core" dockerfile/image that exposes WSGI

Can you give an example for this or explain what do you mean ? 

From https://docs.djangoproject.com/en/3.2/howto/deployment/wsgi/ and https://docs.djangoproject.com/en/3.2/howto/deployment/wsgi/modwsgi/ there doesn't seem to be a way to deploy only the app portion of a Django application (Which Kiwi TCMS is) without the additional web layer.

**Comment by atodorov** [comment]
Closing due to lack of information. 

Feel free to reopen when you can provide the information requested in the previous comment.

**Comment by atodorov** [comment]
>  If WSGI was exposed, it could be integrated directly for performance and simplicity benefit.

That is a bold statement without any backup whatsoever. At https://kiwitcms.readthedocs.io/en/latest/hardware_performance.html we've shown how we've measured a baseline performance and on what hardware configuration. Plus some other hints that we've discovered.  As-is Kiwi TCMS was able to record 35 thousand test execution results/hour.  If that is not enough for you then I suggest:

1) Opening another issue to discuss performance issue
2) Provide details about your setup and similar measurements so we can establish how much of a difference there is

Afterwards we can talk specifics, otherwise it doesn't make sense.
