### ISSUE TITLE
Test Run Edit Errors

### ISSUE THREAD

**Issue by YouWhy** [kiwitcms/Kiwi#2514]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
In our PoC with version 10.2 we are seeing an issue where when we edit a Test Run and try to associate it with a different Test Plan and Build, we are seeing an error message. Please see steps to reproduce.

### Version or commit hash (if applicable)
version 10.2

#### This is how our Test Plans, Versions and Builds for our product SP-X is setup in KIWI.

- Test Plan Hierarchy
![TestPlans](https://user-images.githubusercontent.com/39198291/132033659-7824e6cf-6e57-4bf8-968e-ce4d79d23cc1.PNG)

- Versions
![Versions](https://user-images.githubusercontent.com/39198291/132033816-a34cd5f8-d5b8-4b34-a775-b43a22b271d2.PNG)

- Builds
![Builds](https://user-images.githubusercontent.com/39198291/132033842-7c3d8e1a-de01-44f5-bd9f-27a2ea90585c.PNG)

#### There is a test run linked to PTP Test Plan and we want to change it from PTP to SPX Test Plan.

- PTP Test Plan Summary
![PTP_TestPlanSummary](https://user-images.githubusercontent.com/39198291/132034096-bfb82778-a763-4c45-8281-56edf60c3544.PNG)

- SP-X Test Plan Summary
![SP-X_TestPlanSummary](https://user-images.githubusercontent.com/39198291/132035288-265436f4-932d-4186-a8d8-e296086bd7e3.PNG)

#### This is the Test Run we are trying to edit
![TestRun_Summary](https://user-images.githubusercontent.com/39198291/132034256-40c256be-05bc-4ad5-b6e7-94d1cb657c36.PNG)

### Actual results
When we edit the Test run and try to change Test Plan and Build, we are setting an error....see below..

1. Test Run Edit Page
![TestRun_EditPage](https://user-images.githubusercontent.com/39198291/132034637-ca14d209-d2b5-43c5-b0ce-db7174e13314.PNG)

2. Values Selected from drop down fields.
![TestRun_EditPage_OptionsSelected](https://user-images.githubusercontent.com/39198291/132034706-f36d2c9e-0195-49a3-995d-3225bc3af5de.PNG)

3. Error
![Error](https://user-images.githubusercontent.com/39198291/132034740-d3dd2aeb-2ba1-47d8-80d5-286df37e3745.PNG)

### Expected results
Should be able to edit Test Run properties and save.

**Comment by atodorov** [comment]
The hierarchical TP structure is not the problem. Can be reproduced with https://public.tenant.kiwitcms.org/runs/3311/edit/. 

What I see here:

1) Upon loading the Edit page the Product value is empty. That should have been preloaded. 
2) Originally upon edit you can select a single TP. When selecting the product (b/c it's empty in the first place) the list of test plans changes on the FE, however any selection different from the original TP results in error. 

Most likely the reason is that on the BE the Product and Test Plan fields are filtered and only accept a single value - the original one.  

Notes: The same BE code/form is used in a few other places so need to check why this works in such a way.

**Comment by YouWhy** [comment]
There is some other weird behavior around this..I dont want to write up an issue for everything..but this Test Run Edit feature has some issues and needs to be looked into. I am glad you could reproduce it.
