### ISSUE TITLE
Redmine integration

### ISSUE THREAD

**Issue by ffrpr** [kiwitcms/Kiwi#2518]
Can anyone please explain in clear step-by-step instructions how to integrate Redmine and Kiwi TCMS? We have read the documentation, without any clue on how to do it.. 😥

I've seen a bunch of requests already with this same concern, can anyone please help us? Our organization will be VERY thankful! 🙏

Regards

**Comment by atodorov** [comment]
Duplicate of https://github.com/kiwitcms/Kiwi/issues/2515

On https://kiwitcms.org/support/ and https://github.com/kiwitcms/Kiwi/issues/new/choose it says
"Support and general questions - ask with "kiwi-tcms" tag on Stack Overflow "

Closing since this qualifies as a general question. Ask your support questions on StackOverflow as indicated.

**Comment by ffrpr** [comment]
Your help will be much appreciated:
https://stackoverflow.com/questions/69095017/hot-to-integrate-kiwi-with-redmine
