### ISSUE TITLE
Problem with autentication in Jira external issue tracker 

### ISSUE THREAD

**Issue by zzhelqzkov** [kiwitcms/Kiwi#2556]
### Description of problem
Bug report with issue tracker Jira throws an error  

### Version or commit hash (if applicable)
Bug is reproduced on environment v10.3 and https://public.tenant.kiwitcms.org

### Prerequisite
Configure issue tracker Jira with Base Url, Api username and Api password 

### Steps to Reproduce

1. Open new test run
2. Click on TC bug report    

### Actual results
Throws an error

### Expected results
Should redirect to bug report create page in Jira board 

### Additional info (Python traceback, logs, etc.)
[error-from-browser.log](https://github.com/kiwitcms/Kiwi/files/7338560/error-from-browser.log)

**Comment by atodorov** [comment]
Error message from log:
```
Internal error: JiraError HTTP 401 url: https://appsforfit.atlassian.net/rest/api/2/serverInfo
	text: Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html

	
	response headers = {'Server': 'AtlassianProxy/1.19.3.1', 'Content-Type': 'text/plain', 'Strict-Transport-Security': 'max-age=315360000; includeSubDomains; preload', 'Date': 'Wed, 13 Oct 2021 13:15:47 GMT', 'ATL-TraceId': 'fa673cf0844057c4', 'X-XSS-Protection': '1; mode=block', 'Transfer-Encoding': 'chunked', 'X-Content-Type-Options': 'nosniff', 'Connection': 'keep-alive', 'Expect-CT': 'report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/global-proxy", enforce, max-age=86400'}
	response text = Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html
```

**Comment by atodorov** [comment]
At this point in time I can configure my Jira integration with both an API token and the password used for web login at id.atlassian.net.  Both work fine for RPC connections and I was able to automatically report issues in Jira regardless of which authentication credentials were used. 

It's likely that different JIRA tenants are on different shards and have different settings and that's why I can't reproduce. 

In any case the error message and the [documentation](https://kiwitcms.readthedocs.io/en/latest/modules/tcms.issuetracker.types.html#tcms.issuetracker.types.JIRA) suggest that you use API token instead of a regular password. 

Closing due to lack of reproduceability and information. 

Feel free to reopen if you can reproduce this issue with v11.3 or later and using API token instead of password.
