### ISSUE TITLE
+ buttons for related entries should be disable when parent is null

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#2561]
For example on the TestPlan page try adding Version via the + button popup before any product is selected. 

That will result in a popup where product=null (see URL of popup window). User can still add new entries in the DB, including products but because this is a popup the navigation is missing and they can't go back resulting in an empty page.

**Comment by cmbahadir** [comment]
I would like to work on the fix but before starting, I wanted to be sure about the expected behavior;

1. Is it expected to be working like below for Test Plan and Bug:

> New Test Plan
> ![image](https://user-images.githubusercontent.com/8937774/145255858-8a2d29a7-2861-4fe1-a501-11106dc3a9d1.png)

> New Bug
> ![image](https://user-images.githubusercontent.com/8937774/145257770-16155e2a-b2ad-4463-bd47-ec2ba8e69425.png)

> Where "+" is invisible when there is no parent item.

2. Is it sufficient to make the changes in `mutable.js` files for Test Plan and Bug, because of  the TODO notes, I thought there might be a refactoring planed prior to the fix of this issue?

**Comment by atodorov** [comment]
> Where "+" is invisible when there is no parent item.

I think it's better for the + sign to be visible, but disabled/grayed out. 

> Is it sufficient to make the changes in mutable.js files for Test Plan and Bug?

It should be sufficient but this + button is present on almost every page where you can create objects. You can start only with a single page but it will have to be fixed everywhere otherwise the UI will become inconsistent.
