### ISSUE TITLE
Bugs reported on external sites via Kiwi should have the reporter's ID.

### ISSUE THREAD

**Issue by geeky-neo** [kiwitcms/Kiwi#2591]
**Is your feature request related to a problem? Please describe.**
On integrating Kiwi with Gitlab/Github/Jira via user **tester**, the bugs reported by a team of testers via Kiwi, is logged by the name **tester**, that was used to integrate Kiwi with Gitlab/Github/Jira.

**Describe the solution you'd like**
- A field in user profile page to add Gitlab/Github/Jira ID of the tester's.
So whenever a bug is logged by the tester via Kiwi, the bug contains the tester's Gitlab/Github/Jira ID rather than the one used to integrate Kiwi with Gitlab/Github/Jira.
This will help in identifying the reporter of the bug.

**Describe alternatives you've considered**

**Additional context**

**Comment by atodorov** [comment]
Essentially related to https://github.com/kiwitcms/Kiwi/issues/2383 but is asking for a simpler solution.

> whenever a bug is logged by the tester via Kiwi, the bug contains the tester's Gitlab/Github/Jira ID rather than the one used to integrate Kiwi with Gitlab/Github/Jira.

That for trackers like Bugzilla & Jira that would probably not be a problem, however for GitHub/GitLab (where you have an OAuth app or an integration account) this may not be possible because of their permissioning system. Certainly it needs to be investigated in more details. The fallback solution would be issue tracker customization and a textual mention of the actual user so they can manually switch the reported field (if allowed).
