### ISSUE TITLE
Bug added as hyperlink cannot be deleted

### ISSUE THREAD

**Issue by patelutpal** [kiwitcms/Kiwi#2936]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
In a test run, we added a hyperlink to a bug logged in internal bug tracking system and flagged it as a bug. However, the Test is marked as passed, but we want to delete the hyperlink. We cannot delete the hyperlink.

### Version or commit hash (if applicable)
11.5-Enterprise

### Steps to Reproduce

1.
2.
3.

### Actual results
![image](https://user-images.githubusercontent.com/95658656/194579468-8d8c7b51-a2fe-459e-98f9-de7358dcba6a.png)

![image](https://user-images.githubusercontent.com/95658656/194579603-ebbcf158-d4f4-40cc-be5d-dcf446b20d7c.png)

### Expected results
Should be able to delete a hyperlink, just like having the ability to delete a comment.

**Comment by LtFarns** [comment]
I agree this is an issue. 

Keep in mind it is generally better practice to create a new test run execution rather than removing the associated bug from a previously failed test as consecutive builds of your product are released. Still, misreporting bugs occurs all the time in this industry due to requirements being misinterpreted. 

linkreference_linkreference table appears to be the main link between test executions & bugs. While implementing dynamic edit ability on this relationship may pose too much of a risk, adding a boolean Is_Active column may also suffice as a sufficient work around.
