### ISSUE TITLE
Forbidden (403) CSRF verification failed. Request aborted.  More information is available with DEBUG=True.

### ISSUE THREAD

**Issue by linhvv12** [kiwitcms/Kiwi#2996]
I have problem with kiwitcms when login account with error as below: Forbidden (403) CSRF verification failed. Request aborted.  More information is available with DEBUG=True.

**Comment by atodorov** [comment]
> I have problem with kiwitcms when login account with error as below: Forbidden (403) CSRF verification failed. Request aborted. More information is available with DEBUG=True.

DEBUG=True is useless in this case because it will not tell you why the cross-site request forgery token is missing. 
CSRF is enabled by default on all web forms and it is very unlikely that it would fail because this is a core functionality of the Django framework which Kiwi TCMS is using. We are not doing anything with/around CSRF other than having it enabled.  

The only plausible speculation that I have is that something is removing the csrf cookie somehow.

Provide the following information: 
1. Kiwi TCMS version
2. Is it a stock version or a modified one
3. Exact steps so we can reproduce

Otherwise there is nothing actionable here.

**Comment by atodorov** [comment]
No actionable information here. Reopen when you can provide answers to the questions above.
