### ISSUE TITLE
TestRun has too many updates to stop_date when uploaded via plugin (eg junit-xml)

### ISSUE THREAD

**Issue by michaelkaye** [kiwitcms/Kiwi#3112]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem

I was using automated tools (eg, junit-xml plugin) to upload test case results to kiwi, and after using this, I ended up with what seemed an unbounded number of emails in my inbox.

In this case, I'm uploading a junit file with ~130 test results via the plugin, and so I'm receiving ~130 emails of the form:

First email:
```
Updated on Wed Mar 22 12:54:25 2023
Updated by <tester>

--- stop_date
+++ stop_date
@@ -1 +1 @@
-None
+2023-03-22 12:54:25.104394
```
Followed by many with this equivalent data:
```
--- stop_date
+++ stop_date
@@ -1 +1 @@
-2023-03-22 12:37:06.210075
+2023-03-22 12:37:06.889507
```

Until the final:
```
--- stop_date
+++ stop_date
@@ -1 +1 @@
-2023-03-22 12:37:08.112956
+2023-03-22 12:37:08
```
At a guess, these updates are coming from this method: 

https://github.com/kiwitcms/Kiwi/blob/master/tcms/rpc/api/testexecution.py#L219

which updates the run end date each time an execution updates status.

This might be having problems because what the junit plugin does is create a new execution which is then immediately marked as SUCCESS/FAILURE, which then means the test run is complete (has no executions in state 0) so the run stop_date is set, which is then immediately overwritten by the next test execution coming in.

### Version or commit hash (if applicable)

public.tennant.kiwitcms.org exhibits this behaviour, unsure what version is there.

### Steps to Reproduce

Github action causing the issue (fork and replace TCMS_USERNAME TCMS_PASSWORD secrets to replicate yourself)
https://github.com/michaelkaye/throwaway-test-repo/actions/runs/4490654092

Public tennant history of test run exhibiting the changes:
https://public.tenant.kiwitcms.org/admin/testruns/testrun/5614/history/

### Actual results

Lots of tiny updates that don't provide value

### Expected results

No updates to test plan until formal test run end is sent by the plugin.

**Comment by atodorov** [comment]
I've added this to the backlog. It looks like a bug at first glance. TestRun is supposed to be updated only once when the last TE changes status. That doesn't seem to be the case but I am not sure why.

This API method will need a bit of a freshen-up I think before improving it.

**Comment by atodorov** [comment]
FTR I've discovered what's happening here: 

This problem is visible only when updating results via plugins (maybe not all of them). The junit.xml-plugin in particular will loop over each test case, add it to the test run and then update the status of the resulting test execution:
https://github.com/kiwitcms/junit.xml-plugin/blob/master/tcms_junit_plugin/__init__.py#L116-L120

Because it's the last test execution that is being updated then the API will also update TestRun.stop_date. 

I think the auto-update functionality can be moved to the Kiwi TCMS front-end and remove it from the API method entirely. Then update the plugin(s) to update test execution timestamps & status. Plugins already update TestRun.stop_date as their last operation.
