### ISSUE TITLE
Error launching docker container

### ISSUE THREAD

**Issue by diviatrix** [kiwitcms/Kiwi#313]
### Description of problem
Standard installation with docker image checkout won't work due to problems with ssl certificates. 
Seems they are not included.

### Component (web, API, etc)
docker image

### How often reproducible
100%

### Steps to Reproduce

1. docker pull kiwitcms/kiwi
2. docker run kiwitcms/kiwi

### Actual results
![image](https://user-images.githubusercontent.com/1908948/38732988-ef096ee2-3f28-11e8-93ee-90b7ad018192.png)

### Expected results
It work

**Comment by atodorov** [comment]
Short answer: docker-compose up, read the docs for more info.

**Comment by diviatrix** [comment]
Thanks for info, but there are nuances.

1. In manual command is
```
docker-compose up -d
```
Its fine, but for newbie is not ok, you cant see info and problems.

2. 500 Server error on all pages 

So i did docker-compose up and there is error in log. 
![image](https://user-images.githubusercontent.com/1908948/38736550-0ea3ba44-3f35-11e8-8b7f-60c1cc6ea29d.png)

Is there any way to check what is server setting? I found ssl settings in manual, but there is no any info how to check or change settings, only info how to change certificate.
```
http://kiwitcms.readthedocs.io/en/latest/installing_docker.html#ssl-configuration
```


3. According to documentation, there is info about setting `Debug` to `True`, but no any clue where and how to set. 

Seriously, i'm not such newbie in linux, but i wasted 5 hours just trying to launch Kiwi on my VM. Any clues how to fix ssl error?

**Comment by diviatrix** [comment]
Is there any way to DISABLE ssl?

**Comment by atodorov** [comment]
The SSL log you posted is a warning, not an error so likely not the problem. ISE 500
is usually triggered by Django tracebacks.

There's also a section describing where the httpd logs are stored if you execute docker-compose up. Post the actual log text instead of screenshot of 1 line.

Did you do initial app configuration like described in the docs ?

There's also a section called Customization which tells you how to override settings. There's an entire chapter in the docs which describes all possible settings.

About SSL: yes, modify httpd config to turn it off and rebuild the Docker image.
