### ISSUE TITLE
Using certain unicode characters in a test case causes a "500 Service Error"

### ISSUE THREAD

**Issue by KiraResari** [kiwitcms/Kiwi#327]
### Description of problem
Using certain unicode characters in a test case causes a "500 Service Error"

### Component (web, API, etc)
Web Portal

### Version or commit hash (if applicable)
4.1.3

### How often reproducible
100%

### Steps to Reproduce

1. Create a new test case
2. Enter the unicode character "🔍" in any field (tested for "Summary", "Notes", "Setup", "Breakdown", "Actions" and "Expected Results".
3. Click the [Save]-button

### Actual results
A "500 Service Error" page is displayed

### Expected results
The test case should be created as normal

### Additional info
![2018-04-27 kiwi tcms 500 service error](https://user-images.githubusercontent.com/28697173/39345127-b07260fe-4a21-11e8-80f2-815bf4f87450.png)

**Comment by KiraResari** [comment]
Left-Pointing Magnifying Glass U+1F50D
Took me 35 seconds to find it using Bing.

**Comment by sarzamas** [comment]
I have the same problem with HTTP 500  when saving forms in russian locale
on my local kiwi tcms dev server (docker install)

When I use russian chars in test or bug  forms on my server  - after pushing save button I see  HTTP 500 


When I do the same on public demo server - it works fine - no error


Where I can find vivid instruction about how to switch debug mode instead of HTTP500 on my local server?

those tips written here:
https://kiwitcms.readthedocs.io/en/latest/installing_docker.html
they 
![Change app installation _ Grappelli - Google Chrom](https://user-images.githubusercontent.com/20306235/77070610-96724380-69fb-11ea-8d2f-397e81491178.jpg)
are not vivid at all - I follow them but - still, HTTP500 appears instead of backtrace buffer


here is the log from container STDOUT:
$ docker container logs --tail 1000 kiwi_web

192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "POST /cases/new/ **HTTP/1.1"  500** 11991 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"

192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/patternfly/dist/js/patternfly.min.js HTTP/1.1" 200 38317 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/jquery/dist/jquery.min.js HTTP/1.1" 200 88145 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/datatables.net/js/jquery.dataTables.min.js HTTP/1.1" 200 82650 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/images/kiwi_h20.png HTTP/1.1" 200 2592 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/style/patternfly_override.css HTTP/1.1" 200 412 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 200 39680 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/patternfly/dist/css/patternfly.min.css HTTP/1.1" 200 31684 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/patternfly/dist/css/patternfly-additions.min.css HTTP/1.1" 200 30841 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/patternfly/dist/fonts/PatternFlyIcons-webfont.ttf HTTP/1.1" 200 38876 "https://192.168.20.170/static/patternfly/dist/css/patternfly-additions.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/patternfly/dist/fonts/OpenSans-Regular-webfont.woff2 HTTP/1.1" 200 61980 "https://192.168.20.170/static/patternfly/dist/css/patternfly.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/patternfly/dist/fonts/OpenSans-Light-webfont.woff2 HTTP/1.1" 200 63180 "https://192.168.20.170/static/patternfly/dist/css/patternfly.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/patternfly/dist/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160 "https://192.168.20.170/static/patternfly/dist/css/patternfly.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
192.168.10.70 - - [19/Mar/2020:12:57:10 +0000] "GET /static/images/favicon.ico HTTP/1.1" 200 3494 "https://192.168.20.170/cases/new/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"

**Comment by sarzamas** [comment]
@atodorov
ticket may be closed

as it is configuration issue

maybe need to update documentation... cause I spent a day to find out a reason of HTTP500

**Comment by atodorov** [comment]
@sarzamas - please send a pull request for documentation updates where you think is unclear instructions. 

Also what language is that, which requires the `utf8mb4` charset ? We should probably document this  as well.

**Comment by sarzamas** [comment]
@atodorov

for language charset support in form - utf8 is sufficient
for emoji support  in forms - utf8mb4 is necessary


Regarding pull request... there is nothing on this theme in docs yet except this ticket
should be new wiki page describing configuration of  localization/emodji support in mariaDB instances (ust using my steps above)

**Comment by atodorov** [comment]
@sarzamas - public.tenant is hosted with Postgres (utf8 charset) and emojis seem to be supported:
https://public.tenant.kiwitcms.org/case/8579/

I have changed the default charset & collation for MariaDB to utf8mb4 and it doesn't break any existing tests so I think it is safe to leave it as default.

Also added a short section in the configuration page to point out this may be something an admin would like to look at. It really depends on what you language is and how your DB server is configured (also what languages does it support) so it's hard to give any more specific information.

**Comment by deltoro05** [comment]
> Left-Pointing Magnifying Glass U+1F50D Took me 35 seconds to find it using Bing (searched for "🔍 unicode") Also see https://unicode-table.com/de/1F50D/
> 
> Anyway, I could successfully reproduce this on the life demo site as well on first try. Have fun =^,^=

This URL has changed to https://symbl.cc/de/1F50D/, it will be cool if you fix it )

**Comment by deltoro05** [comment]
> Left-Pointing Magnifying Glass U+1F50D Took me 35 seconds to find it using Bing (searched for "🔍 unicode") Also see https://unicode-table.com/de/1F50D/
> 
> Anyway, I could successfully reproduce this on the life demo site as well on first try. Have fun =^,^=

This URL https://unicode-table.com/ has changed to https://symbl.cc/
