### ISSUE TITLE
Missing test plans in search test plan page

### ISSUE THREAD

**Issue by mnive** [kiwitcms/Kiwi#3313]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
In the Search test plan page while expanding the parent plan, some child test plans are not listed in the view

### Version or commit hash (if applicable)
12.5

### Steps to Reproduce

1. Create a parent test plan with multi level nested child test plans.
2. From the Search Test Plans page, filter by product and select the test plan created in step-1
3. Expand the parent level test plans to view the test plan hierarchy

### Actual results
All the test plans are not listed and some test plans are missing in the view. 
Click on the parent level test plan and click on expand arrow, all the test plans are listed there.

![image](https://github.com/kiwitcms/Kiwi/assets/133168663/8fe6ed80-de6a-4f7d-8f35-cda06a3c015d)

### Expected results
All the test plans should be listed as we expand the parent level test plan

**Comment by atodorov** [comment]
@mnive can you replicate the same on public.tenant.kiwitcms.org ? 

> From the Search Test Plans page, filter by product and select the test plan created in step-1

Q2: Do all of the 5 child test plans have the same product as the parent ? 

Notes:
my suspicion is that TP-963 is slightly different from the rest and from its parent and that's why is is missing from the search.  I can replicate a similar scenario with https://public.tenant.kiwitcms.org/plan/7288/another-parent-tp

TP-7288 and it's first 4 children have type: Acceptance while  TP-7293: Level 5 has a Type of Function.  When I filter the search results by Type and select `Acceptance` as the filter value the fifth child doesn't appear in the results. When I don't filter by Type then the fifth child appears in the results.

The way child-parent relationships are displayed in the search table is that child rows are groupped together and then hidden from view before the table is rendered: 
https://github.com/kiwitcms/Kiwi/blob/master/tcms/testplans/static/testplans/js/search.js#L127-L134


So this looks like an issue with managing expectations because the search table can't show rows which are being filtered out due to the search criteria. 

I will keep this issue open for now and see if we can idicate that the resulting child-set may not be complete !
