### ISSUE TITLE
Attachment attached to wrong object

### ISSUE THREAD

**Issue by somenewacc** [kiwitcms/Kiwi#3320]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
There is a case when added attachments can be attached to wrong object (TestRun instead of TestCase).

### Version or commit hash (if applicable)
12.5

### Steps to Reproduce

1. Start editing Test Case (in example -- https://public.tenant.kiwitcms.org/case/18845/). Add attachment to it:
![image](https://github.com/kiwitcms/Kiwi/assets/62895232/d713cf58-16d0-4568-87d2-993061bddec6)

2. Without saving test case editor (you can close the tab), create new test run in another tab. You will see that attachments from Test Case are now in TestRun (https://public.tenant.kiwitcms.org/runs/6722/):
![image](https://github.com/kiwitcms/Kiwi/assets/62895232/cc2ce3a7-ed2d-4de6-8e09-6307f99d811f)

3. Now you can go back to test case editor and save it. You will see that there are no attachment attached to it:
![image](https://github.com/kiwitcms/Kiwi/assets/62895232/798657ae-0bbd-4a70-9deb-824e1b1993b0)

### Actual results
Attachments that was added to **test case** are attached to **test run**

### Expected results
Attachments that was added to **test case** are attached to **test case**

**Comment by atodorov** [comment]
This is a side effect of having support for inline attachments in the editor and having these attachments be shown under the object being saved. https://github.com/kiwitcms/Kiwi/blob/master/tcms/signals.py#L253

The editor doesn't know about test plan or test cases, etc b/c they may not be created yet. Even if they are passing this information along is not straight forward because the same editor must work for multiple different scenarios. Thus the editor will attach files temporarily to the currently logged in user (same as what GitHub does). 

Then we'll try to move those files under the last object which gets saved in the current session so that these files also appear in the Attachments card. This obviously can't work reliably if you create multiple objects in parallel and save them in a different order to which the files were attached in the editor. 

Closing as can't fix.  If you have ideas on how to reliably resolve this feel free to open a pull request and we'll evaluate.
