### ISSUE TITLE
Your connection is not secure: After updating SSL key

### ISSUE THREAD

**Issue by bishnupradhan** [kiwitcms/Kiwi#359]
http://kiwitcms.readthedocs.io/en/latest/installing_docker.html#ssl-configuration
We follow the above links and update the localhost.key and localhost.crt files under etc/kiwitcms/ssl/
and do docker-compose up.
But the in the browsers, it reflects as 'Your connection is not secure'.

**Comment by atodorov** [comment]
Yes, because you are probably using a self-signed SSL key and browsers by default will not trust that. If you want the warning gone then either create your own certificate authority and install it's certificates into all browsers that will access Kiwi or invest the money to buy an SSL certificate by a well-known certificate authority.
