### ISSUE TITLE
Unable to open any Test Plans.

### ISSUE THREAD

**Issue by AkashSharma93** [kiwitcms/Kiwi#455]
### Description of problem
Not able to open a test plan after creating it.

### Component (web, API, etc)
* API

### Version or commit hash (if applicable)
* Tag: v5.1

### How often reproducible
* Happens every time.

### Steps to Reproduce
1. Login to kiwi as the root user. 
2. Create a new test plan with basic details like Name, Product name, version, and . description.
3. Click on the Create Test Plan button.

### Actual results
Observation:
* The app shows a 404 - page not found. URL: https://127.0.0.1:8000/plan/id/plan_name
* The Test plan is displayed in the dashboard, but it can't be opened from there as well.

### Expected results
The test plan page should display the details of the test plan.

### Additional info
Installed Kiwi using docker, on a macbook pro (MacOS High Sierra)

**Comment by Prome88** [comment]
Did you set base URL under:
1. Admin
2. Everything else
3. Sites
4. Domain name

**Comment by okainov** [comment]
@Prome88 actually it's also IMO questionable - why should I set this "base url" at all in simple default case? You know current base address, just use it, don't mess with replacing base domain. Maybe it makes sense for some complicated cases but in general it's overhead, I think

**Comment by atodorov** [comment]
@okainov this setting is used by `get_full_url()`, see #380, which is used in quite a lot of places. From what I can tell it is only necessary when sending emails because the application itself can't reliably figure out its own domain name.

That said the rest of the places where this method is used should be updated and link/redirect to URLs without the domain part. Follow #380 for that progress.
