### ISSUE TITLE
New test run cannot be created from test cases

### ISSUE THREAD

**Issue by bishnupradhan** [kiwitcms/Kiwi#463]
Description of problem
Test cases cannot be added to existing test run
New test run cannot be created from test cases
Component (web, API, etc)
Web

How often reproducible
Always.

Steps to Reproduce
Open test plan
Select cases
Click on Create new test run / Add to existing test run
Actual results
Internal server error 500.

Expected results
Test cases added to test run.

**Comment by atodorov** [comment]
Can't reproduce on demo. Provide exact version and detailed steps to reproduce.

**Comment by Muvidevlopers** [comment]
Version used V5.1

**Comment by mdrabicki** [comment]
Have the same problem both on v 4.x and 5.1. Version instaled and updated using docker.

**Comment by atodorov** [comment]
Provide steps to reproduce which work on the demo instance or provide traceback logs. Otherwise I can't reproduce and there's nothing I can do.

**Comment by mdrabicki** [comment]
I cannot reproduce this on demo. Also I see 500 error but in log/httpd/ssl_error_log and log/httdp/error_log there is no traceback or any mention about this error. Debug option is set on True. Where can I find traceback logs?

**Comment by debayanMuvi** [comment]
I am facing same problem 5.1. Version instaled and updated using docker.

**Comment by debayanMuvi** [comment]
I tried again cleaning all the images in the docker and then again i pulled and did the setup locally it working now going to put it in server with docker 5.1

**Comment by mdrabicki** [comment]
Ok, I figured it out. The problem occurred because as "default tester" I entered an email address which is linked with my account and root account. So steps should look like this.
1. Create new user
2. A an admin create the 2nd user with this same email
3. Open test plan
4. Create a new test run
5. As "Default tester" enter email from the first step
6. Confirm test run

In my opinion, email should be obligatory unique even when is set by the admin.
