### ISSUE TITLE
No information show after selecting the filter option of component

### ISSUE THREAD

**Issue by LZ-001** [kiwitcms/Kiwi#465]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
cannot find any avalible component options while filtering cases

### Component (web, API, etc)
web

### How often reproducible
always

### Steps to Reproduce

1.create a test plan
2.create a test case
3.In cases tab view, select the test case and add components to the case
4.In cases tab view, select filter -> component

### Actual results
no componet shown to be selected 
<img width="1530" alt="err" src="https://user-images.githubusercontent.com/12823650/43756832-0ad31e22-9a49-11e8-8fc1-62f84d586978.png">

### Expected results
should show components info for selecting

**Comment by Prome88** [comment]
Reproducible on 4.2.

**Comment by chenchangjiang** [comment]
Category filed has same bug need fix.

**Comment by atodorov** [comment]
@chenchangjiang if you can help that's fine. Please send a PR for code review.

**Comment by Prome88** [comment]
We are using search by Summary / Tags but currently it cannot fully replace category + component filter.

Example:
-> Test Case 1 has tag A & B
-> Test Case 2 has tag A
-> Test Case 3 has tag B

If we try to get only test case 1 and input tag A,B into search the application returns all three test cases. So for tags to be really efficient they would need to allow AND / OR operators and possibly even NOT.

**Comment by atodorov** [comment]
Note to self: after the TP page is completely redesigned it will contain a simple toolbar filtering functionality. The page also contains a popup functionality to search & add test cases via the TC search page. The same can be reused as advanced search & filter for the toolbar instead of duplicating that functionality on the page. Any additional logic such as AND/OR support and multiple criteria should be added to the TC Search page instead.

**Comment by atodorov** [comment]
https://github.com/kiwitcms/Kiwi/issues/2048
