### ISSUE TITLE
Update from 4.2 to 5.2 hangs docker containter

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#482]
Upgrading from 4.2 to 5.2 via instructions posted on http://kiwitcms.org/blog/kiwi-tcms-team/2018/08/07/kiwi-tcms-52/ .

After running the last command _docker exec -it kiwi_web /Kiwi/manage.py migrate_ the docker container (kiwi_web) hung with:

(13)Permission denied: AH00058: Error retrieving pid file /run/httpd/httpd.pid
AH00059: Remove it before continuing if it is corrupted.

**Comment by atodorov** [comment]
In 5.2 changelog: `Docker image now executes with uid 1001 instead of root`

so this means we don't have access to directories owned by root.

`rm /run/httpd/httpd.pid` was part of the earlier versions, where the Docker image was built on top of centos/httpd. This command is from there.

1) Make sure you are indeed running the latest version which should not run as root, the above error makes me think you may be running an older version.

2) An easy way to get root shell inside a container is `docker exec -u root` and you should fix filesystem permissions if necessary.

**Comment by andrazh** [comment]
Just to be sure - are you referring to running Docker container as a non-root user or are you referring to services running inside of that Docker container?
After running those two "docker pull ..." commands, executing "docker exec -u root -ti container_id bash" doesn't do the trick - it fails with the same "Error response from daemon: Container ... a is restarting, wait until the container is running" error we get when trying to finish the upgrade procedure with "docker exec -it kiwi_web /Kiwi/manage.py migrate".

**Comment by atodorov** [comment]
> Just to be sure - are you referring to running Docker container as a non-root user or are you referring to services running inside of that Docker container?

I mean whatever is executed inside the container (Apache, Django, Python, bash) will not be executed with uid 1001 instead of root.

The crashing container is a sign that something isn't working and before you can get the container not to crash do not try to execute migrate because you may skew up your database.  

I have no idea what's going on but a few things to try: 

1) When starting via docker-compose up don't pass `-d`. Apache and MySQL logs should be printed on the console in the host.

2) Try fetching the latest image (maybe on another host) and start from scratch with clean docker volumes for uploads and database.

3) Try `docker run --entrypoint /bin/bash` so you can get a shell. Then try starting the processess manually to figure out what is the error.


^^^ I suspect some file ownership & permissions are not as they should be or maybe some of the mountpoints in `docker-compose.yml`. See changelog for the paths that have been changed and update your pre-existing volumes if necessary.

Without a particular error message or logs I can't help you further. Feel-free to reopen if you can provide more info.

**Comment by andrazh** [comment]
Hi there,

I'm back with a bit more information - but regarding the logs, I didn't find much more - starting docker-compose without "-d" showed only what we already pasted in one of the posts above. Today I've created two VMs for testing purposes - one with Ubuntu 16.04 and Oracle Linux 7.5 on the other. On both VMs I've installed Kiwi from scratch. It turned out that OL VM works fine, on Ubuntu we bump into the same error. Below is the list of commands for both installations together with a few lines from Docker logs.

```
Ubuntu 16.04:

apt-get install docker.io docker-compose
docker pull kiwitcms/kiwi
git clone https://github.com/kiwitcms/Kiwi.git
cd Kiwi
docker-compose up -d
root@kiwi-tmp2:/home/tc/Kiwi# docker logs --tail 10 --follow kiwi_web
AH00059: Remove it before continuing if it is corrupted.
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00058: Error retrieving pid file /run/httpd/httpd.pid


Oracle Linux 7.5:

yum install docker-engine
systemctl start docker
systemctl enable docker
curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
docker pull kiwitcms/kiwi
git clone https://github.com/kiwitcms/Kiwi.git
cd Kiwi/
[root@kiwi-tmp3 Kiwi]# docker-compose up
Starting kiwi_db ... done
Starting kiwi_web ... done
Attaching to kiwi_db, kiwi_web
db_1   | 180822 10:09:39 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
db_1   | 180822 10:09:39 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
web_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
web_1  | httpd (pid 6) already running
kiwi_web exited with code 0
```

I'm practically sure nothing special was needed (besides the same installation steps) on our first installation on Ubuntu 16.04  - the one we're trying to upgrade and that works fine with Kiwi TCMS version 4.2.

**Comment by atodorov** [comment]
Do you have a UID 1001 on the Ubuntu system? On Red Hat derivative distributions (which Oracle Linux is) ids below 1000 are reserved for system use and the first user is created with uid 1001. (which I think Docker will map to the processes from the container). 

Ubuntu probably doesn't have such uid created.

FYI in the future you can ask support questions in Stack Overflow using the "kiwi-tcms" tag:
https://stackoverflow.com/questions/tagged/kiwi-tcms

**Comment by andrazh** [comment]
Ubuntu VM has a user with uid 1001 as well, actually the username was the same as well. Something other was problematic.
Because I know way to little about Docker to find the cause of the problem I decided to copy /var/lib/docker/volumes to Oracle Linux VM, pulled kiwitcms images and after running "docker-compose up" I executed the last part of the upgrade procedure - "docker exec -it kiwi_web /Kiwi/manage.py migrate".

**Comment by andrazh** [comment]
It seems I was way too fast with my previous claim how everything works fine. :) It turned out it actually doesn't have to do anything with the upgrade, because a clean install has problems on its own, rather sooner than later.

My next try was with current stable Fedora. Created a user with UID 1001 and added it do docker group, so that logged-in as this user, the following commands were executed:

 docker pull kiwitcms/kiwi
 cd Kiwi/
 docker-compose up -d
 docker exec -it kiwi_web /Kiwi/manage.py migrate
 docker exec -it kiwi_web /Kiwi/manage.py createsuperuser

The result seemed to be OK. Until I tried to upload a file. Running "docker exec -u root -ti container_id bash" revealed that inside the container /Kiwi/uploads was owned by root user. After "chown 1001 /Kiwi/uploads" uploading attachments works fine.
But the behaviour described above still manifests - quite fast, it seems after restarting Docker service. When kiwi_web comes to this "restarting mode", running this helps:

```
dockerclean () {
    docker ps --all --format="{{.ID}}" | xargs docker kill
    docker ps --all --format="{{.ID}}" | xargs docker rm
    docker images --all --format="{{.ID}}" | xargs docker rmi
}
```

This clears everything in Docker. Persistent volumes stay untouched, after running "docker-compose up -d" again, Kiwi TCMS starts successfully. But that cannot be normal?
What I also noticed is that in Kiwi/tcms/settings/common.py DEBUG already is set to True. However, nothing useful is visible. Running "docker-compose up" without "-d" flag doesn't reveal any useful information:

``` web_1  | httpd (pid 8) already running
 web_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
 kiwi_web exited with code 0```

The middle line is displayed always, even when everything is running without problem.

**Comment by familyman-131** [comment]
hi
have exactly same problem on ubuntu 16.04 with latest kiwi release, latest docker
have followed by this instruction https://kiwitcms.readthedocs.io/en/latest/installing_docker.html
cannot do _docker exec_ because container is permanently restarted

**Comment by atodorov** [comment]
@familyman-131 do not comment on closed issues because nobody will pay attention to them. Open a question on StackOverflow containing enough information so the problem can be investigated.
