### ISSUE TITLE
RFC: GitHub pull request workflow integration

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#700]
I hate it that in many teams testing comes after the fact and despite all the talks about being agile testing is still kind of isolated! This should be an integral part of the entire engineering process. 

Since currently many folks use the GitHub pull request workflow it makes sense to collect ideas how Kiwi TCMS could integrate with that. What I imagine we could do is:

* When new PR is opened/updated parse changelog and search for `TP-xx` and/or `TC-xx` references and create a new TestRun automatically.
* Provide status reports on pull requests when all tests are executed (or even per TC)
* If PR is still open update with more statuses when new test cases are added to test plan

Something like this:
![github_kiwitcms_pr_status](https://user-images.githubusercontent.com/1002300/50796919-cee89e80-12db-11e9-89e6-ae2df78f4b7f.png)

Any more wild ideas? Share them in the comments. Vote :+1: (to-right corner) for the ones you want to use.

**Comment by okainov** [comment]
Seems nice from the first sight, however, I see the whole point of such a PR checks as _quick_ and _automated_ checks.
If you want your QA engineer to commit to monitor new test runs and execute them (manual testing, right?) in, let's say, 12 hours, your QA engineer will hate you and eventually quit. So you will have intern-students-monkeys performing these tests and then quitting after half a year because it's boring, awful and not interesting.

**Comment by atodorov** [comment]
Initial work has been done in https://github.com/kiwitcms/github-app/ which for now only synchronizes content based on web hook. The proposal outlined in comment #0 would be implemented as part of fixing https://github.com/kiwitcms/github-app/issues. <--- comment/follow here if interested. Closing this one.
