### ISSUE TITLE
Bugs are not appearing in exported XML 

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#79]
### Description of problem
Bugs from test run are not in XML when exported

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
04ee63372bac82dd614dc44ba20a10e14ae4016e

### How often reproducible
always

### Steps to Reproduce

1. Create some test run with tests
2. Execute tests, put bug into some test case runs
3. Press "Export to XML" button

### Actual results
XML contains empty "\<bugs/\>" section

### Expected results
Bugs should be in XML

**Comment by atodorov** [comment]
I have confirmed this problem. However how do you intend to use the exported XML file? Frankly I was thinking about removing the CVS/XML export functionality because we do have an API layer. 

I will look at this problem in more details in the next couple of days, but please let me know what are you planning to do with the XML files.

**Comment by GodfatherThe** [comment]
I don't really need it (at least so far), just was playing with the tool and noticed this :)
