### ISSUE TITLE
Do you have plans to add other languages?

### ISSUE THREAD

**Issue by yunpengb** [kiwitcms/Kiwi#831]
### Description of problem
Hello, do you have plans to add other languages?

### Version or commit hash (if applicable)
--

### Actual results
only english

### Expected results
support Chinese language

**Comment by atodorov** [comment]
We do have Chinese translations, how ever they are incomplete. Because we don't speak Chinese there isn't much we can do about it.

We use Crowdin as our translation system and it sends pull requests to this repository whenever new translations are available. We have community members contributing heavily to Slovenian and French translation. If you'd like to contribute on Chinese translation see 
https://kiwitcms.readthedocs.io/en/latest/contribution.html#translation

That said Kiwi TCMS is a Django application and it will automatically try to use the language configured in your operating system or browser. There's no menu to switch the language from the user interface.

For Linux this is usually controlled by the `LANG` environment variable.

**Comment by yunpengb** [comment]
Thank you for your reply, It sounds interesting. 
I'll read this link. Maybe I can do something.
