### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#89]
While trying to run\install Kiwi on my machine, I've met some issues:

- In the repo node_modules folder doesn't exist. So I had to comment lines 161-164 in common settings when running w\o Docker.
- While running make docker-image, error (1) appears

> Step 4/23 : RUN rpm -Uhv https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm &&     yum -y --setopt=tsflags=nodocs install centos-release-scl &&     yum -y --setopt=tsflags=nodocs install rh-python35 gcc mariadb-devel     libxml2-devel libxslt-devel httpd-devel mod_wsgi mod_ssl npm &&     yum -y update --setopt=tsflags=nodocs
 ---> Running in 93f5d3f42ea7
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm - transfer failed

Probably URL should be changed to https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm

- Error (2), but from another mirrors it was fetched successfully

>Loaded plugins: fastestmirror, ovl
ftp://mirror.vtti.vt.edu/centos/7/os/x86_64/repodata/0c34273ad0292747ee5e15c047d3e51c67ca59861a446972db45d71abacc7ad7-primary.sqlite.bz2: [Errno 14] curl#7 - "Failed to connect to 2001:468:c80:2133:0:b0e2:0:9874: Cannot assign requested address"
Trying other mirror.
ftp://mirror.bytemark.co.uk/centos/7/os/x86_64/repodata/0c34273ad0292747ee5e15c047d3e51c67ca59861a446972db45d71abacc7ad7-primary.sqlite.bz2: [Errno 14] curl#7 - "Failed to connect to 2001:41c8:20:5e6::10: Cannot assign requested address"
Trying other mirror.

- Before all the magic, one need Docker (ok, this was simple) and docker-compose, but it's not written anywhere

- I was not able to locate manual for production run, so how do I make it accessible not only for localhost, but for the network?

- After all, system appears, but the interface looks ugly (see screenshot)
![image](https://user-images.githubusercontent.com/918446/32162475-62c1b152-bd59-11e7-9dad-3418989049e6.png)
Any ideas, what's wrong with the interface? How can I make it nicer?

**Comment by atodorov** [comment]
OK, so the node_modules/ directory needs to be populated by `npm install patternfly`. I agree that this needs to be documented b/c it is missing. 

However Kiwi TCMS is supposed to be executed as a Docker container, not installed as a stand alone application. 

The rest of the issues you are seeing are due to some changes in CentOS/EPEL repositories. Obviously they have changed their URL structure and also updated some of the RPM versions. Will update Dockerfile for that.

The ugly UI is because you are missing the node_modules/. This is a Django based project so you also need to execute collectstatic before the UI can find all of its images and CSS. See that the Dockerfile is doing and do the same.

> Before all the magic, one need Docker (ok, this was simple) and docker-compose, but it's not written anywhere

Have you read chapter 2 "Running Kiwi TCMS as Docker container" ?
http://kiwitcms.readthedocs.io/en/latest/installing_docker.html

It describes everything you need in order to build a Docker container and start it.


> I was not able to locate manual for production run, so how do I make it accessible not only for localhost, but for the network?

The container binds to all addresses so just access the machine via its FQDN.

**Comment by GodfatherThe** [comment]
Even from Docker container UI is the same.
>It describes everything you need in order to build a Docker container and start it.
As I wrote, it's simple, but it's missing part "Install docker. Install docker-compose".

**Comment by atodorov** [comment]
@GodfatherThe I actually didn't understand some of the previous comments but the last one makes things more clear for me. Please see #92. I think it covers your concerns. Please review it if possible.

About development flow:

you are supposed to be running Kiwi TCMS via ./manage.py runserver for local development and testing. This is the standard way of working on Django related projects. You don't need docker for development.  I think my previous comments have confused you and I'm sorry for this.
